<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Backpack\PermissionManager\app\Http\Controllers\UserCrudController as OriginalUserCrudController;

class UserCrudController extends OriginalUserCrudController
{
    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub

        $this->crud->addButtonFromModelFunction('line', 'sms', 'sms', 'beginning');
        $this->crud->addButtonFromModelFunction('line', 'mail', 'mail', 'beginning');
    }
}
